using System;
using System.Linq;
using System.Text.RegularExpressions;
using Fallout.Common.Utilities;
using Fallout.Common.Utilities.Collections;
using Scriban;

namespace Fallout.Solutions;

/// <summary>
/// Shared emit logic for the strongly-typed <c>[Solution]</c> accessor (<c>Solution.g.cs</c>).
/// Referenced by both the in-compiler <c>StronglyTypedSolutionGenerator</c> (the ns2.0 toggle
/// fallback) and the net10 pre-build <c>Fallout.Solution.Codegen</c> console (the default), so the
/// two paths produce byte-identical output.
/// </summary>
public static class SolutionEmitter
{
    public static string Emit(Solution solution, string memberName, bool fancyNaming)
    {
        var declaration = GetDeclaration(solution);

        // lang=csharp
        return $"""
            // <auto-generated/>

            using Fallout.Persistence.Solution.Model;
            using Fallout.Solutions;
            using Fallout.Common.IO;
            using System.Runtime.CompilerServices;

            {declaration}
            """;

        string GetDeclaration(IProjectContainer container, string folderName = null)
        {
            var prefix = new string(GetDelimiterChar(), container.Descendants(x => x.Parent).Count() + 1);
            var model = new
            {
                IsSolution = container is Solution,
                SolutionReference = container is Solution ? "this" : "solution",
                Name = GetEscapedName(container switch
                {
                    Solution => memberName,
                    SolutionFolder folder => folderName ?? folder.Name,
                    _ => throw new ArgumentOutOfRangeException(nameof(container), container, null)
                }),
                Projects = container.Projects.OrderBy(x => x.Name).Select(x => new
                {
                    x.Name,
                    EscapedName = GetEscapedName(x.Name),
                }),
                Folders = container.SolutionFolders.OrderBy(x => x.Name).Select(x => new
                {
                    x.Name,
                    TypeName = $"{prefix}{GetEscapedName(x.Name)}",
                    EscapedName = GetEscapedName(x.Name),
                }),
                Declarations = container.SolutionFolders.OrderBy(x => x.Name)
                    .Select(x => GetDeclaration(x, $"{prefix}{GetEscapedName(x.Name)}")).ToArray(),
            };

            // lang=csharp
            var template = Template.Parse("""
                {{~ if is_solution ~}}
                internal class {{ name }}(SolutionModel model, AbsolutePath path) : Fallout.Solutions.Solution(model, path)
                {{~ else ~}}
                internal class {{ name }}(SolutionFolderModel model, Fallout.Solutions.Solution solution) : Fallout.Solutions.SolutionFolder(model, solution)
                {{~ end ~}}
                {
                {{~ for project in projects ~}}
                    public Fallout.Solutions.Project {{ project.escaped_name }} => this.GetProject("{{ project.name }}");
                {{~ end ~}}

                {{~ for folder in folders ~}}
                    public {{ folder.type_name }} {{ folder.escaped_name }} => Unsafe.As<{{ folder.type_name }}>(this.GetSolutionFolder("{{ folder.name }}"));
                {{~ end ~}}

                {{~ for declaration in declarations ~}}
                    {{ declaration }}
                {{~ end ~}}
                }
                """);
            return template.Render(model);

            // C# identifiers can't start with a digit and can only contain
            // letters/digits/underscore. Folders like `00-Build` would otherwise
            // produce invalid output (nuke-build/nuke#1581).
            string GetEscapedName(string name)
            {
                name = name
                    .Replace(".", GetDelimiterChar().ToString())
                    .ReplaceRegex(@$"[^A-Za-z0-9{GetDelimiterChar()}]",
                        _ => $"{GetDelimiterChar()}");

                if (Regex.IsMatch(name, @"^[0-9]"))
                    return $"{GetDelimiterChar()}{name}";

                return name;
            }

            char GetDelimiterChar()
            {
                const char fancyNameDelimiter = 'ꞏ'; // U+A78F
                const char defaultDelimiter = '_';

                return fancyNaming ? fancyNameDelimiter : defaultDelimiter;
            }
        }
    }
}
